Update iwd SysVinit script for correctness

diff --git a/meta-edtwardy/recipes-connectivity/iwd/files/iwd b/meta-edtwardy/recipes-connectivity/iwd/files/iwd
--- a/meta-edtwardy/recipes-connectivity/iwd/files/iwd
+++ b/meta-edtwardy/recipes-connectivity/iwd/files/iwd
@@ -2,90 +2,63 @@
 ### BEGIN INIT INFO
 # Provides:          iwd
 # Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
+# Required-Stop:     $rmeote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Start daemon at boot time
 # Description:       Enable service provided by daemon.
 ### END INIT INFO
 
-prog=/usr/libexec/iwd
-
 name=iwd
+prog=/usr/libexec/$name
 pid_file="/var/run/$name.pid"
 
 . /etc/init.d/functions
 
-get_pid() {
-    cat "$pid_file"
+RC=0
+
+start() {
+    start-stop-daemon -S -b --pidfile $pid_file -m -x $prog
+    status=$?
+    if [ $status != 0 ]; then
+        >&2 printf '%s\n' "Couldn't start $name"
+        RC=1
+    fi
 }
 
-is_running() {
-    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
+stop() {
+    start-stop-daemon -K -x $prog
+}
+
+status() {
+    if [ -f $pid_file ] && [ -d /proc/$(cat $pid_file) ]; then
+        printf '%s\n' "Running"
+    else
+        printf '%s\n' "Stopped"
+    fi
 }
 
 case "$1" in
     start)
-    if is_running; then
-        echo "Already started"
-    else
-        echo "Starting $name"
-        start-stop-daemon -S -b --oknodo --pidfile $pid_file -m \
-                          --startas $prog
-        if [ $? != 0 ]; then
-            echo "Unable to start $name"
-        fi
-    fi
-    ;;
+        start
+        ;;
+
     stop)
-    if is_running; then
-        echo -n "Stopping $name.."
-        kill `get_pid`
-        for i in 1 2 3 4 5 6 7 8 9 10
-        # for i in `seq 10`
-        do
-            if ! is_running; then
-                break
-            fi
+        stop
+        ;;
 
-            echo -n "."
-            sleep 1
-        done
-        echo
-
-        if is_running; then
-            echo "Not stopped; may still be shutting down or shutdown may have failed"
-            exit 1
-        else
-            echo "Stopped"
-            if [ -f "$pid_file" ]; then
-                rm "$pid_file"
-            fi
-        fi
-    else
-        echo "Not running"
-    fi
-    ;;
     restart)
-    $0 stop
-    if is_running; then
-        echo "Unable to stop, will not attempt to start"
-        exit 1
-    fi
-    $0 start
-    ;;
-    status)
-    if is_running; then
-        echo "Running"
-    else
-        echo "Stopped"
-        exit 1
-    fi
-    ;;
-    *)
-    echo "Usage: $0 {start|stop|restart|status}"
-    exit 1
-    ;;
-esac
+        stop
+        sleep 3
+        start
+        ;;
 
-exit 0
+    status)
+        status
+        ;;
+
+    *)
+        echo "Usage: $0 {start|stop|restart|status}"
+        RC=1
+        ;;
+esac
